name: xl_plus
description: >
  Implement accelerometer and pointer or touch fueled parallax
  animations with a bespoke XL layering paradigm. Gyroscope supported.
version: 1.0.0
repository: https://github.com/kishormainali/xl
issue_tracker: https://github.com/kishormainali/xl/issues

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  sensors_plus: ^4.0.1

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

